
/* Drop Tables */

DROP TABLE YO_ADMIN CASCADE CONSTRAINTS;
DROP TABLE YO_COST CASCADE CONSTRAINTS;
DROP TABLE YO_PATIENT CASCADE CONSTRAINTS;
DROP TABLE YO_GUARDIAN CASCADE CONSTRAINTS;
DROP TABLE YO_PRESCRIPTION CASCADE CONSTRAINTS;
DROP TABLE YO_REQ CASCADE CONSTRAINTS;
DROP TABLE YO_USER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE YO_ADMIN
(
	AD_DEPTH varchar2(30),
	AD_GRADE varchar2(20),
	US_AD_ID varchar2(20) NOT NULL,
	PRIMARY KEY (US_AD_ID)
);


CREATE TABLE YO_COST
(
	CO_SUPPORT number,
	US_CO_ID varchar2(20) NOT NULL
);


CREATE TABLE YO_GUARDIAN
(
	GU_PHONE varchar2(30),
	US_GU_ID varchar2(20) NOT NULL,
	PRIMARY KEY (US_GU_ID)
);


CREATE TABLE YO_PATIENT
(
	PA_UNIQUE varchar2(50),
	PA_DISEASE varchar2(30),
	US_GU_PA_ID varchar2(20) NOT NULL,
	US_PA_ID varchar2(20) NOT NULL,
	PRIMARY KEY (US_PA_ID)
);


CREATE TABLE YO_PRESCRIPTION
(
	PR_DISNAME varchar2(20) NOT NULL,
	PR_EXPLANATION varchar2(200),
	PR_CURE varchar2(200),
	PRIMARY KEY (PR_DISNAME)
);


CREATE TABLE YO_REQ
(
	RE_NUM number NOT NULL,
	RE_DATE date,
	RE_COMMENT varchar2(200),
	US_RE_ID varchar2(20) NOT NULL,
	PRIMARY KEY (RE_NUM)
);


CREATE TABLE YO_USER
(
	US_ID varchar2(20) NOT NULL,
	US_PW varchar2(20),
	US_NAME varchar2(20),
	US_AGE number,
	US_IMG blob,
	PRIMARY KEY (US_ID)
);



/* Create Foreign Keys */

ALTER TABLE YO_PATIENT
	ADD FOREIGN KEY (US_GU_PA_ID)
	REFERENCES YO_GUARDIAN (US_GU_ID)
;


ALTER TABLE YO_ADMIN
	ADD FOREIGN KEY (US_AD_ID)
	REFERENCES YO_USER (US_ID)
;


ALTER TABLE YO_COST
	ADD FOREIGN KEY (US_CO_ID)
	REFERENCES YO_USER (US_ID)
;


ALTER TABLE YO_GUARDIAN
	ADD FOREIGN KEY (US_GU_ID)
	REFERENCES YO_USER (US_ID)
;


ALTER TABLE YO_PATIENT
	ADD FOREIGN KEY (US_PA_ID)
	REFERENCES YO_USER (US_ID)
;


ALTER TABLE YO_REQ
	ADD FOREIGN KEY (US_RE_ID)
	REFERENCES YO_USER (US_ID)
;



